<a href="https://colab.research.google.com/github/ahmadhusain-25/target/blob/master/TM%201%262%20Data%20Analyze%20-%20DSA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#IMPORT DATA

In [4]:
import pandas as pd

In [5]:
pd.read_csv('sample - data penjualan - Orders.csv', delimiter=';')

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/08/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.00,419.136
1,2,CA-2016-152156,11/08/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.00,219.582
2,3,CA-2016-138688,06/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.62,2,0.00,68.714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,9.575.775,5,0.45,-383.031
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.368,2,0.20,25.164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9983,9990,CA-2014-110422,1/21/2014,1/23/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.248,3,0.20,41.028
9984,9991,CA-2017-121258,2/26/2017,03/03/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.96,2,0.00,156.332
9985,9992,CA-2017-121258,2/26/2017,03/03/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.576,2,0.20,193.932
9986,9993,CA-2017-121258,2/26/2017,03/03/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6,4,0.00,13.32
9987,9994,CA-2017-119914,05/04/2017,05/09/2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.16,2,0.00,72.948

In [6]:
data = pd.read_csv('sample - data penjualan - Orders.csv', delimiter=';')

In [7]:
data

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/08/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.00,419.136
1,2,CA-2016-152156,11/08/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.00,219.582
2,3,CA-2016-138688,06/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.62,2,0.00,68.714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,9.575.775,5,0.45,-383.031
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.368,2,0.20,25.164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9983,9990,CA-2014-110422,1/21/2014,1/23/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.248,3,0.20,41.028
9984,9991,CA-2017-121258,2/26/2017,03/03/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.96,2,0.00,156.332
9985,9992,CA-2017-121258,2/26/2017,03/03/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.576,2,0.20,193.932
9986,9993,CA-2017-121258,2/26/2017,03/03/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6,4,0.00,13.32
9987,9994,CA-2017-119914,05/04/2017,05/09/2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.16,2,0.00,72.948

# IMPORT DATA DARI GOOGLE DRIVE

In [8]:
# membuat variabel url ('edit?pli=1&gid=1961927276#' diganti 'export?format=csv&') (untuk format "csv" bisa disesuaikan dengan keinginan, ex: bisa excel,SPSS,json,dll)
url_drive = 'https://docs.google.com/spreadsheets/d/1KjCn7DOHLKAYMvmTP13SF0cb2nmwL49IFbvfb6HPzjk/export?format=csv&gid=1961927276'

In [9]:
#Membuat variabel untuk membaca data url (#untuk 'csv' disesuaikan dengan format diatasnya)
data_url = pd.read_csv(url_drive)

In [10]:
data_url

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Unnamed: 21,Unnamed: 22
0,1.0,US-2021-103800,03/01/2021,07/01/2021,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...","16,448",2.0,"0,2","5,5512",rata-rata sales,"228,2258539"
1,2.0,US-2021-112326,04/01/2021,08/01/2021,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,"3,54",2.0,"0,8","-5,487",NaN,per order ID
2,3.0,US-2021-112326,04/01/2021,08/01/2021,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,OFF-LA-10003223,Office Supplies,Labels,Avery 508,"11,784",3.0,"0,2","4,2717",NaN,NaN
3,4.0,US-2021-112326,04/01/2021,08/01/2021,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,"272,736",3.0,"0,2","-64,7748",NaN,NaN
4,5.0,US-2021-141817,05/01/2021,12/01/2021,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,...,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,"19,536",3.0,"0,2","4,884",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10191,10192.0,US-2024-156720,30/12/2024,03/01/2025,Standard Class,JM-15580,Jill Matthias,Consumer,United States,Loveland,...,OFF-FA-10003472,Office Supplies,Fasteners,Bagged Rubber Bands,"3,024",3.0,"0,2","-0,6048",NaN,NaN
10192,10193.0,US-2024-143259,30/12/2024,03/01/2025,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,...,TEC-PH-10004774,Technology,Phones,Gear Head AU3700S Headset,"90,93",7.0,0,"2,7279",NaN,NaN
10193,10194.0,CA-2024-143500,30/12/2024,03/01/2025,Standard Class,HO-15230,Harry Olson,Consumer,Canada,Charlottetown,...,OFF-BI-10004040,Office Supplies,Binders,Wilson Jones Impact Binders,"3,024",3.0,"0,2","-0,6048",NaN,NaN
10194,NaN,10194,NaN,NaN,NaN,804,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"2326534,354",NaN,NaN,NaN,NaN,NaN
10195,NaN,"228,2258539","228,2258539",NaN,NaN,"2893,699446",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# ANALISIS DESKRIPTIF

In [11]:
# cek tipe data dan missing value
data_url.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10196 entries, 0 to 10195
Data columns (total 23 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          10194 non-null  float64
 1   Order ID        10196 non-null  object
 2   Order Date      10195 non-null  object
 3   Ship Date       10194 non-null  object
 4   Ship Mode       10194 non-null  object
 5   Customer ID     10196 non-null  object
 6   Customer Name   10194 non-null  object
 7   Segment         10194 non-null  object
 8   Country/Region  10194 non-null  object
 9   City            10194 non-null  object
 10  State/Province  10194 non-null  object
 11  Postal Code     10194 non-null  object
 12  Region          10194 non-null  object
 13  Product ID      10194 non-null  object
 14  Category        10194 non-null  object
 15  Sub-Category    10194 non-null  object
 16  Product Name    10194 non-null  object
 17  Sales           10195 non-null  object
 18  Quantity        10194 non-null  float64
 19  Discount        10194 non-null  object
 20  Profit          10194 non-null  object
 21  Unnamed: 21     1 non-null      object
 22  Unnamed: 22     2 non-null      object
dtypes: float64(2), object(21)
memory usage: 1.8+ MB

In [14]:
data_url['Order Date'] = pd.to_datetime(data_url['Order Date'], dayfirst=True, errors='coerce')

In [21]:
# Clean numeric columns and calculate correlation
for col in ['Sales', 'Discount', 'Profit']:
    data_url[col] = data_url[col].astype(str).str.replace(',', '.').astype(float)

corr = data_url[['Sales', 'Quantity', 'Discount', 'Profit']].corr()
print(corr)

             Sales  Quantity  Discount    Profit
Sales     1.000000  0.198457 -0.027756  0.481460
Quantity  0.198457  1.000000  0.007475  0.066145
Discount -0.027756  0.007475  1.000000 -0.218882
Profit    0.481460  0.066145 -0.218882  1.000000